import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import SessionTimeout from "./(dashboard)/SessionTimeout";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${mulish.className}`}>
        <SessionTimeout />
        {children}
      </body>
    </html>
  );
}